/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolEmbedRouteImport } from './routes/tool.embed'
import { Route as AdminUnlockRouteImport } from './routes/admin.unlock'
import { Route as AdminPosterRouteImport } from './routes/admin.poster'
import { Route as AdminNowBuildingRouteImport } from './routes/admin.now-building'
import { Route as AdminLockRouteImport } from './routes/admin.lock'
import { Route as AdminGameRouteImport } from './routes/admin.game'
import { Route as ActionsSlugRouteImport } from './routes/actions.$slug'
import { Route as ActionsReportAChangeStartRouteImport } from './routes/actions.report-a-change.start'
import { Route as ActionsCheckDocumentsStartRouteImport } from './routes/actions.check-documents.start'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolEmbedRoute = ToolEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => ToolRoute,
} as any)
const AdminUnlockRoute = AdminUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosterRoute = AdminPosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNowBuildingRoute = AdminNowBuildingRouteImport.update({
  id: '/now-building',
  path: '/now-building',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLockRoute = AdminLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameRoute = AdminGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AdminRoute,
} as any)
const ActionsSlugRoute = ActionsSlugRouteImport.update({
  id: '/actions/$slug',
  path: '/actions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsReportAChangeStartRoute =
  ActionsReportAChangeStartRouteImport.update({
    id: '/actions/report-a-change/start',
    path: '/actions/report-a-change/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActionsCheckDocumentsStartRoute =
  ActionsCheckDocumentsStartRouteImport.update({
    id: '/actions/check-documents/start',
    path: '/actions/check-documents/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/tool': typeof ToolRouteWithChildren
  '/actions/$slug': typeof ActionsSlugRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/now-building': typeof AdminNowBuildingRoute
  '/admin/poster': typeof AdminPosterRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/tool/embed': typeof ToolEmbedRoute
  '/admin/': typeof AdminIndexRoute
  '/actions/check-documents/start': typeof ActionsCheckDocumentsStartRoute
  '/actions/report-a-change/start': typeof ActionsReportAChangeStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/tool': typeof ToolRouteWithChildren
  '/actions/$slug': typeof ActionsSlugRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/now-building': typeof AdminNowBuildingRoute
  '/admin/poster': typeof AdminPosterRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/tool/embed': typeof ToolEmbedRoute
  '/admin': typeof AdminIndexRoute
  '/actions/check-documents/start': typeof ActionsCheckDocumentsStartRoute
  '/actions/report-a-change/start': typeof ActionsReportAChangeStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/tool': typeof ToolRouteWithChildren
  '/actions/$slug': typeof ActionsSlugRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/now-building': typeof AdminNowBuildingRoute
  '/admin/poster': typeof AdminPosterRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/tool/embed': typeof ToolEmbedRoute
  '/admin/': typeof AdminIndexRoute
  '/actions/check-documents/start': typeof ActionsCheckDocumentsStartRoute
  '/actions/report-a-change/start': typeof ActionsReportAChangeStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/tool'
    | '/actions/$slug'
    | '/admin/game'
    | '/admin/lock'
    | '/admin/now-building'
    | '/admin/poster'
    | '/admin/unlock'
    | '/tool/embed'
    | '/admin/'
    | '/actions/check-documents/start'
    | '/actions/report-a-change/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/tool'
    | '/actions/$slug'
    | '/admin/game'
    | '/admin/lock'
    | '/admin/now-building'
    | '/admin/poster'
    | '/admin/unlock'
    | '/tool/embed'
    | '/admin'
    | '/actions/check-documents/start'
    | '/actions/report-a-change/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/tool'
    | '/actions/$slug'
    | '/admin/game'
    | '/admin/lock'
    | '/admin/now-building'
    | '/admin/poster'
    | '/admin/unlock'
    | '/tool/embed'
    | '/admin/'
    | '/actions/check-documents/start'
    | '/actions/report-a-change/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ToolRoute: typeof ToolRouteWithChildren
  ActionsSlugRoute: typeof ActionsSlugRoute
  ActionsCheckDocumentsStartRoute: typeof ActionsCheckDocumentsStartRoute
  ActionsReportAChangeStartRoute: typeof ActionsReportAChangeStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tool/embed': {
      id: '/tool/embed'
      path: '/embed'
      fullPath: '/tool/embed'
      preLoaderRoute: typeof ToolEmbedRouteImport
      parentRoute: typeof ToolRoute
    }
    '/admin/unlock': {
      id: '/admin/unlock'
      path: '/unlock'
      fullPath: '/admin/unlock'
      preLoaderRoute: typeof AdminUnlockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/poster': {
      id: '/admin/poster'
      path: '/poster'
      fullPath: '/admin/poster'
      preLoaderRoute: typeof AdminPosterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/now-building': {
      id: '/admin/now-building'
      path: '/now-building'
      fullPath: '/admin/now-building'
      preLoaderRoute: typeof AdminNowBuildingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lock': {
      id: '/admin/lock'
      path: '/lock'
      fullPath: '/admin/lock'
      preLoaderRoute: typeof AdminLockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game': {
      id: '/admin/game'
      path: '/game'
      fullPath: '/admin/game'
      preLoaderRoute: typeof AdminGameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/actions/$slug': {
      id: '/actions/$slug'
      path: '/actions/$slug'
      fullPath: '/actions/$slug'
      preLoaderRoute: typeof ActionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/report-a-change/start': {
      id: '/actions/report-a-change/start'
      path: '/actions/report-a-change/start'
      fullPath: '/actions/report-a-change/start'
      preLoaderRoute: typeof ActionsReportAChangeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/check-documents/start': {
      id: '/actions/check-documents/start'
      path: '/actions/check-documents/start'
      fullPath: '/actions/check-documents/start'
      preLoaderRoute: typeof ActionsCheckDocumentsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGameRoute: typeof AdminGameRoute
  AdminLockRoute: typeof AdminLockRoute
  AdminNowBuildingRoute: typeof AdminNowBuildingRoute
  AdminPosterRoute: typeof AdminPosterRoute
  AdminUnlockRoute: typeof AdminUnlockRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGameRoute: AdminGameRoute,
  AdminLockRoute: AdminLockRoute,
  AdminNowBuildingRoute: AdminNowBuildingRoute,
  AdminPosterRoute: AdminPosterRoute,
  AdminUnlockRoute: AdminUnlockRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ToolRouteChildren {
  ToolEmbedRoute: typeof ToolEmbedRoute
}

const ToolRouteChildren: ToolRouteChildren = {
  ToolEmbedRoute: ToolEmbedRoute,
}

const ToolRouteWithChildren = ToolRoute._addFileChildren(ToolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ToolRoute: ToolRouteWithChildren,
  ActionsSlugRoute: ActionsSlugRoute,
  ActionsCheckDocumentsStartRoute: ActionsCheckDocumentsStartRoute,
  ActionsReportAChangeStartRoute: ActionsReportAChangeStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
