/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VersionSemverRouteImport } from './routes/version.$semver'
import { Route as AdminVersionsRouteImport } from './routes/admin.versions'
import { Route as AdminUnlockRouteImport } from './routes/admin.unlock'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminPosterRouteImport } from './routes/admin.poster'
import { Route as AdminNowBuildingRouteImport } from './routes/admin.now-building'
import { Route as AdminLockRouteImport } from './routes/admin.lock'
import { Route as AdminGameRouteImport } from './routes/admin.game'
import { Route as ActionsSlugRouteImport } from './routes/actions.$slug'
import { Route as ActionsReportAChangeStartRouteImport } from './routes/actions.report-a-change.start'
import { Route as ActionsCheckDocumentsStartRouteImport } from './routes/actions.check-documents.start'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VersionSemverRoute = VersionSemverRouteImport.update({
  id: '/version/$semver',
  path: '/version/$semver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVersionsRoute = AdminVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnlockRoute = AdminUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosterRoute = AdminPosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNowBuildingRoute = AdminNowBuildingRouteImport.update({
  id: '/now-building',
  path: '/now-building',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLockRoute = AdminLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameRoute = AdminGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AdminRoute,
} as any)
const ActionsSlugRoute = ActionsSlugRouteImport.update({
  id: '/actions/$slug',
  path: '/actions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsReportAChangeStartRoute =
  ActionsReportAChangeStartRouteImport.update({
    id: '/actions/report-a-change/start',
    path: '/actions/report-a-change/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActionsCheckDocumentsStartRoute =
  ActionsCheckDocumentsStartRouteImport.update({
    id: '/actions/check-documents/start',
    path: '/actions/check-documents/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/backlog': typeof BacklogRoute
  '/changelog': typeof ChangelogRoute
  '/feedback': typeof FeedbackRoute
  '/tool': typeof ToolRoute
  '/actions/$slug': typeof ActionsSlugRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/now-building': typeof AdminNowBuildingRoute
  '/admin/poster': typeof AdminPosterRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/version/$semver': typeof VersionSemverRoute
  '/admin/': typeof AdminIndexRoute
  '/actions/check-documents/start': typeof ActionsCheckDocumentsStartRoute
  '/actions/report-a-change/start': typeof ActionsReportAChangeStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/changelog': typeof ChangelogRoute
  '/feedback': typeof FeedbackRoute
  '/tool': typeof ToolRoute
  '/actions/$slug': typeof ActionsSlugRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/now-building': typeof AdminNowBuildingRoute
  '/admin/poster': typeof AdminPosterRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/version/$semver': typeof VersionSemverRoute
  '/admin': typeof AdminIndexRoute
  '/actions/check-documents/start': typeof ActionsCheckDocumentsStartRoute
  '/actions/report-a-change/start': typeof ActionsReportAChangeStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/backlog': typeof BacklogRoute
  '/changelog': typeof ChangelogRoute
  '/feedback': typeof FeedbackRoute
  '/tool': typeof ToolRoute
  '/actions/$slug': typeof ActionsSlugRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/lock': typeof AdminLockRoute
  '/admin/now-building': typeof AdminNowBuildingRoute
  '/admin/poster': typeof AdminPosterRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/unlock': typeof AdminUnlockRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/version/$semver': typeof VersionSemverRoute
  '/admin/': typeof AdminIndexRoute
  '/actions/check-documents/start': typeof ActionsCheckDocumentsStartRoute
  '/actions/report-a-change/start': typeof ActionsReportAChangeStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/backlog'
    | '/changelog'
    | '/feedback'
    | '/tool'
    | '/actions/$slug'
    | '/admin/game'
    | '/admin/lock'
    | '/admin/now-building'
    | '/admin/poster'
    | '/admin/subscribers'
    | '/admin/unlock'
    | '/admin/versions'
    | '/version/$semver'
    | '/admin/'
    | '/actions/check-documents/start'
    | '/actions/report-a-change/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backlog'
    | '/changelog'
    | '/feedback'
    | '/tool'
    | '/actions/$slug'
    | '/admin/game'
    | '/admin/lock'
    | '/admin/now-building'
    | '/admin/poster'
    | '/admin/subscribers'
    | '/admin/unlock'
    | '/admin/versions'
    | '/version/$semver'
    | '/admin'
    | '/actions/check-documents/start'
    | '/actions/report-a-change/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/backlog'
    | '/changelog'
    | '/feedback'
    | '/tool'
    | '/actions/$slug'
    | '/admin/game'
    | '/admin/lock'
    | '/admin/now-building'
    | '/admin/poster'
    | '/admin/subscribers'
    | '/admin/unlock'
    | '/admin/versions'
    | '/version/$semver'
    | '/admin/'
    | '/actions/check-documents/start'
    | '/actions/report-a-change/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BacklogRoute: typeof BacklogRoute
  ChangelogRoute: typeof ChangelogRoute
  FeedbackRoute: typeof FeedbackRoute
  ToolRoute: typeof ToolRoute
  ActionsSlugRoute: typeof ActionsSlugRoute
  VersionSemverRoute: typeof VersionSemverRoute
  ActionsCheckDocumentsStartRoute: typeof ActionsCheckDocumentsStartRoute
  ActionsReportAChangeStartRoute: typeof ActionsReportAChangeStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/version/$semver': {
      id: '/version/$semver'
      path: '/version/$semver'
      fullPath: '/version/$semver'
      preLoaderRoute: typeof VersionSemverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/versions': {
      id: '/admin/versions'
      path: '/versions'
      fullPath: '/admin/versions'
      preLoaderRoute: typeof AdminVersionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unlock': {
      id: '/admin/unlock'
      path: '/unlock'
      fullPath: '/admin/unlock'
      preLoaderRoute: typeof AdminUnlockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/poster': {
      id: '/admin/poster'
      path: '/poster'
      fullPath: '/admin/poster'
      preLoaderRoute: typeof AdminPosterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/now-building': {
      id: '/admin/now-building'
      path: '/now-building'
      fullPath: '/admin/now-building'
      preLoaderRoute: typeof AdminNowBuildingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lock': {
      id: '/admin/lock'
      path: '/lock'
      fullPath: '/admin/lock'
      preLoaderRoute: typeof AdminLockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game': {
      id: '/admin/game'
      path: '/game'
      fullPath: '/admin/game'
      preLoaderRoute: typeof AdminGameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/actions/$slug': {
      id: '/actions/$slug'
      path: '/actions/$slug'
      fullPath: '/actions/$slug'
      preLoaderRoute: typeof ActionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/report-a-change/start': {
      id: '/actions/report-a-change/start'
      path: '/actions/report-a-change/start'
      fullPath: '/actions/report-a-change/start'
      preLoaderRoute: typeof ActionsReportAChangeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/check-documents/start': {
      id: '/actions/check-documents/start'
      path: '/actions/check-documents/start'
      fullPath: '/actions/check-documents/start'
      preLoaderRoute: typeof ActionsCheckDocumentsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGameRoute: typeof AdminGameRoute
  AdminLockRoute: typeof AdminLockRoute
  AdminNowBuildingRoute: typeof AdminNowBuildingRoute
  AdminPosterRoute: typeof AdminPosterRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminUnlockRoute: typeof AdminUnlockRoute
  AdminVersionsRoute: typeof AdminVersionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGameRoute: AdminGameRoute,
  AdminLockRoute: AdminLockRoute,
  AdminNowBuildingRoute: AdminNowBuildingRoute,
  AdminPosterRoute: AdminPosterRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminUnlockRoute: AdminUnlockRoute,
  AdminVersionsRoute: AdminVersionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BacklogRoute: BacklogRoute,
  ChangelogRoute: ChangelogRoute,
  FeedbackRoute: FeedbackRoute,
  ToolRoute: ToolRoute,
  ActionsSlugRoute: ActionsSlugRoute,
  VersionSemverRoute: VersionSemverRoute,
  ActionsCheckDocumentsStartRoute: ActionsCheckDocumentsStartRoute,
  ActionsReportAChangeStartRoute: ActionsReportAChangeStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
